const root=document.documentElement,button=document.querySelector('.lang'),nodes=document.querySelectorAll('[data-en][data-zh]');
function language(lang){const zh=lang==='zh';root.classList.add('fade');setTimeout(()=>{root.lang=zh?'zh-Hant':'en';nodes.forEach(n=>n.textContent=n.dataset[zh?'zh':'en']);button.children[0].classList.toggle('active',!zh);button.children[2].classList.toggle('active',zh);document.title=zh?'黃暐宸｜人工智慧研究者':'Wesley Huang | AI Researcher';localStorage.setItem('portfolio-language',lang)},140);setTimeout(()=>root.classList.remove('fade'),310)}
button.addEventListener('click',()=>language(root.lang==='en'?'zh':'en'));language(localStorage.getItem('portfolio-language')||'en');document.getElementById('year').textContent=new Date().getFullYear();
if(matchMedia('(pointer:fine)').matches&&!matchMedia('(prefers-reduced-motion:reduce)').matches)document.querySelectorAll('.magnetic').forEach(el=>{el.addEventListener('pointermove',e=>{const r=el.getBoundingClientRect(),x=(e.clientX-r.left)/r.width-.5,y=(e.clientY-r.top)/r.height-.5;el.style.transform=`translate(${x*7}px,${y*5}px) scaleX(1.045)`});el.addEventListener('pointerleave',()=>el.style.transform='');el.addEventListener('pointerdown',()=>el.style.transform+=' scale(.97)')});

document.querySelectorAll('.archive-toggle').forEach(toggle=>toggle.addEventListener('click',()=>{const card=toggle.closest('.archive-card'),open=card.classList.toggle('open');toggle.setAttribute('aria-expanded',String(open))}));
document.querySelectorAll('.filters button').forEach(filter=>filter.addEventListener('click',()=>{document.querySelectorAll('.filters button').forEach(b=>b.classList.remove('active'));filter.classList.add('active');document.querySelectorAll('.archive-card').forEach(card=>{const show=filter.dataset.filter==='all'||card.dataset.category===filter.dataset.filter;card.classList.toggle('filtered-out',!show)})}));
const lightbox=document.querySelector('.lightbox'),lightboxBody=document.querySelector('.lightbox-body');
function showPreview(src,type){lightboxBody.replaceChildren();if(type==='pdf'){const frame=document.createElement('iframe');frame.src=src;frame.title='Document preview';lightboxBody.append(frame)}else{const image=document.createElement('img');image.src=src;image.alt='Expanded achievement image';lightboxBody.append(image)}lightbox.showModal()}
document.querySelectorAll('.image-media').forEach(el=>el.addEventListener('click',()=>showPreview(el.dataset.src,'image')));
document.querySelectorAll('.media-open').forEach(el=>el.addEventListener('click',()=>showPreview(el.dataset.src,el.dataset.type)));
document.querySelector('.lightbox-close').addEventListener('click',()=>lightbox.close());lightbox.addEventListener('click',e=>{if(e.target===lightbox)lightbox.close()});
